package edu.grinnell.csc207.soundsofsorting.sorts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.sortevents.CompareEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.CopyEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SwapEvent;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i   the first index to swap
     * @param j   the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * 
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> bubbleSort(T[] arr) {
        List<SortEvent<T>> ret = new ArrayList<>();
        for (int i = 0; i < arr.length - 1; i++) {
            for (int j = 0; j < arr.length - 1 - i; j++) {
                ret.add(new CompareEvent<>(j, j + 1));
                if (arr[j].compareTo(arr[j + 1]) > 0) {
                    swap(arr, j, j + 1);
                    ret.add(new SwapEvent<>(j, j + 1));
                }
            }
        }
        return ret;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * 
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> selectionSort(
            T[] arr) {
        List<SortEvent<T>> ret = new ArrayList<>();
        for (int i = 0; i < arr.length - 1; i++) {
            int minIndex = i;
            for (int j = i + 1; j < arr.length; j++) {
                ret.add(new CompareEvent<>(j, minIndex));
                if (arr[j].compareTo(arr[minIndex]) < 0) {
                    minIndex = j;
                }
            }
            swap(arr, i, minIndex);
            ret.add(new SwapEvent<>(i, minIndex));
        }
        return ret;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * 
     * <pre>
     * [ i elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> insertionSort(
            T[] arr) {
        List<SortEvent<T>> ret = new ArrayList<>();
        for (int i = 0; i < arr.length; i++) {
            for (int j = i; j > 0 && arr[j].compareTo(arr[j - 1]) < 0; j--) {
                ret.add(new CompareEvent<>(j, j - 1));
                swap(arr, j, j - 1);
                ret.add(new SwapEvent<>(j, j - 1));
            }
        }
        return ret;
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> mergeSort(
            T[] arr) {
        T[] scratch = Arrays.copyOf(arr, arr.length);
        return mergeSortH(arr, scratch, 0, arr.length);
    }

    /**
     * Helper procedure that merge sorts the specified section of the array
     * 
     * @param <T>     the carrier type of the array
     * @param arr     the array to sort
     * @param scratch a secondary array to use for the merge operation
     * @param lo      the index at which the algorithm should start sorting
     *                (inclusive)
     * @param hi      the index at which the algorithm should stop sorting
     *                (exclusive)
     * @return the sort events generated by this sort
     */
    private static <T extends Comparable<? super T>> List<SortEvent<T>> mergeSortH(
            T[] arr, T[] scratch, int lo, int hi) {
        List<SortEvent<T>> ret = new ArrayList<>();
        if (hi <= lo + 1) {
            return ret;
        }
        int mid = (hi - lo) / 2 + lo;
        for (SortEvent<T> event : mergeSortH(arr, scratch, lo, mid)) {
            ret.add(event);
        }
        for (SortEvent<T> event : mergeSortH(arr, scratch, mid, hi)) {
            ret.add(event);
        }
        for (SortEvent<T> event : merge(arr, scratch, lo, mid, hi)) {
            ret.add(event);
        }
        return ret;
    }

    /**
     * Helper procedure that performs the merge operation of merge sort
     * 
     * @param <T>     the carrier type of the array
     * @param arr     the array to sort
     * @param scratch a secondary array to use for the merge operation
     * @param lo      the index at which the first subarray begins (inclusive)
     * @param mid     the index at which the second subarray begins (inclusive)
     * @param hi      the index at which the second subarray ends (exclusive)
     * @return the sort events generated by this sort
     */
    private static <T extends Comparable<? super T>> List<SortEvent<T>> merge(
            T[] arr, T[] scratch, int lo, int mid, int hi) {
        List<SortEvent<T>> ret = new ArrayList<>();
        int i = lo;
        int j = mid;
        int k = 0;
        while (i < mid && j < hi) {
            ret.add(new CompareEvent<>(i, j));
            if (arr[i].compareTo(arr[j]) < 0) {
                scratch[k] = arr[i];
                i++;
            } else {
                scratch[k] = arr[j];
                j++;
            }
            k++;
        }
        if (i == mid) {
            while (j < hi) {
                scratch[k] = arr[j];
                j++;
                k++;
            }
        } else {
            while (i < mid) {
                scratch[k] = arr[i];
                i++;
                k++;
            }
        }
        for (int s = lo, t = 0; s < hi; s++, t++) {
            arr[s] = scratch[t];
            ret.add(new CopyEvent<T>(scratch[t], s));
        }
        return ret;
    }

    /**
     * Sorts the array according to the quick sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> quickSort(T[] arr) {
        return quickSortH(arr, 0, arr.length);
    }

    /**
     * Helper procedure that quick sorts the sepcified section of the array
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @param lo  the index at which the algorithm should start sorting (inclusive)
     * @param hi  the index at which the algortihm should stop sorting (exclusive)
     * @return the sort events generated by this sort
     */
    private static <T extends Comparable<? super T>> List<SortEvent<T>> quickSortH(
            T[] arr, int lo, int hi) {
        List<SortEvent<T>> ret = new ArrayList<>();
        if (hi <= lo + 1) {
            return ret;
        }
        if (hi == lo + 2) {
            ret.add(new CompareEvent<>(lo, lo + 1));
            if (arr[lo].compareTo(arr[lo + 1]) > 0) {
                swap(arr, lo, lo + 1);
                ret.add(new SwapEvent<>(lo, lo + 1));
            }
            return ret;
        }
        int mid = (hi - lo) / 2 + lo;
        int pivotIndex = medianIndex(arr, lo, mid, hi - 1);
        swap(arr, hi - 1, pivotIndex);
        ret.add(new SwapEvent<>(hi - 1, pivotIndex));
        int i = lo;
        int j = hi - 2;
        while (j > i) {
            ret.add(new CompareEvent<>(i, hi - 1));
            if (arr[i].compareTo(arr[hi - 1]) > 0) {
                ret.add(new CompareEvent<>(j, hi - 1));
                if (arr[j].compareTo(arr[hi - 1]) < 0) {
                    swap(arr, i, j);
                    ret.add(new SwapEvent<>(i, j));
                } else {
                    j--;
                }
            } else {
                i++;
            }
        }
        swap(arr, hi - 1, i);
        ret.add(new SwapEvent<>(hi - 1, i));
        for (SortEvent<T> event : quickSortH(arr, lo, i)) {
            ret.add(event);
        }
        for (SortEvent<T> event : quickSortH(arr, i + 1, hi)) {
            ret.add(event);
        }
        return ret;
    }

    /**
     * Procedure that finds the median of three values in an array
     * 
     * @param <T> the carrier type of the array
     * @param arr the array that holds the values being compared
     * @param lo  one index to look at
     * @param mid another index to look at
     * @param hi  a third index to look at
     * @return the array of the median value
     */
    private static <T extends Comparable<? super T>> int medianIndex(
            T[] arr, int lo, int mid, int hi) {
        T[] temp = Arrays.copyOf(arr, 3);
        temp[0] = arr[lo];
        temp[1] = arr[mid];
        temp[2] = arr[hi];
        selectionSort(temp);
        if (temp[1] == arr[lo]) {
            return lo;
        } else if (temp[1] == arr[mid]) {
            return mid;
        } else {
            return hi;
        }
    }

    /**
     * Sorts the array according to the gnome sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> gnomeSort(T[] arr) {
        List<SortEvent<T>> ret = new ArrayList<>();
        int i = 0;
        while (i < arr.length) {
            if(i > 0) {
                ret.add(new CompareEvent<>(i, i - 1));
            }
            if (i == 0 || arr[i].compareTo(arr[i - 1]) >= 0) {
                i++;
            } else {
                swap(arr, i, i - 1);
                ret.add(new SwapEvent<>(i, i - 1));
                i--;
            }
        }
        return ret;
    }

    /**
     * Sorts the array accoring to the list of sort events
     * 
     * @param <T>    the carrier type of the array
     * @param l      the array to sort
     * @param events a list of the events with which to sort
     */
    public static <T> void eventSort(T[] l, List<SortEvent<T>> events) {
        for (SortEvent<T> event : events) {
            event.apply(l);
        }
    }
}
